# Generated by Django 2.2.16 on 2022-07-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_ar', models.CharField(max_length=300, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/article')),
                ('index', models.IntegerField()),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ArticleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/article_details')),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ar', models.TextField(null=True)),
                ('index', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_details', to='articlesapp.Article')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
