# Generated by Django 2.2.16 on 2022-07-05 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='articledetails',
            name='text_ar',
        ),
        migrations.RemoveField(
            model_name='articledetails',
            name='text_en',
        ),
    ]
