# Generated by Django 2.2.16 on 2022-07-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('coupon', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
