stages:
  - test

variables:
  MYSQL_USER: root
  MYSQL_PASSWORD: test_db_pass
  MYSQL_ROOT_PASSWORD: test_db_pass
  MYSQL_DATABASE: clinic
  

pytest:
  stage: test
  image: python:3.8
  image: docker/compose:latest
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker-compose -f local.yml build
    # Ensure celerybeat does not crash due to non-existent tables
    - docker-compose -f local.yml run --rm web python manage.py migrate
    - docker-compose -f local.yml up -d
  script:
    - docker-compose -f local.yml run web pytest
