# Generated by Django 2.2.16 on 2022-07-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=300)),
                ('index', models.IntegerField()),
                ('cv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cvapp.cv')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ScientificDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_degree', models.CharField(max_length=300)),
                ('index', models.IntegerField()),
                ('cv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scientific_degrees', to='cvapp.cv')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=300)),
                ('index', models.IntegerField()),
                ('cv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='cvapp.cv')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=300)),
                ('index', models.IntegerField()),
                ('cv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cvapp.cv')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=300)),
                ('index', models.IntegerField()),
                ('cv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cvapp.cv')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
