# Generated by Django 2.2.16 on 2022-07-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/service')),
                ('index', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/service_details')),
                ('text', models.TextField()),
                ('index', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_details', to='servicesapp.Service')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
