# Generated by Django 2.2.16 on 2022-07-04 17:51

from django.db import migrations, models

import clinic.userapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", clinic.userapp.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_development_api_user",
            field=models.BooleanField(
                default=False,
                help_text="indicate if this user could be used in developer only private APIs like create statistics endpoints.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Phone"
            ),
        ),
    ]
